development:
  adapter: mysql
  database: joemetric_dev
  host: localhost
test:
  adapter: mysql
  database: joemetric_test
  host: localhost
staging:
  adapter: mysql
  database: joemetric_stage
  host: 0.0.0.0
  port: 3036
production:
  adapter: mysql
  database: joemetric_prod
  host: 0.0.0.0
  port: 3036
