desc "Run unit tests"
task :test do
  output = `xcodebuild -target "Unit Test" -configuration Debug -sdk iphonesimulator2.1`
  if output.grep(/^Executed \d+ tests, with (\d+) failures/).any? do |line|
      line =~ /(\d+) failures/
      $1.to_i > 0
    end
    exit_code = 1
  else
    exit_code = 0
  end
  puts output.gsub(/^\s+setenv.*\n/, '')
  exit exit_code
end

desc "Clean all targets"
task :clean do
  sh 'xcodebuild -alltargets -configuration Release clean'
  sh 'xcodebuild -alltargets -configuration Debug clean'
end

task :default => [:test]
