desc "Run unit tests"
task :test do
  exit_code = 0
  output = `xcodebuild -target "Unit Test" -configuration Debug -sdk iphonesimulator2.1`
  output.each do |line| 
    case 
    when line =~ /passed/         : exit_code = pass(line)    
    when line =~ /^\s+setenv.*\n/ : nil
    when line =~ /(\d+) failures/
      if $1.to_i > 0
        exit_code = fail(line)
      else
        exit_code = pass(line)
      end
    else 
      puts line
    end
  end
  exit exit_code
end

desc "Clean all targets"
task :clean do
  sh 'xcodebuild -alltargets -configuration Release clean'
  sh 'xcodebuild -alltargets -configuration Debug clean'
end

task :default => [:test]

def pass(line)
  color(line, :green)
  return 0
end

def fail(line)
  color(line, :red)
  return 1
end

def color(output, color_type)
  print "#{send(color_type.to_s)}#{output}#{reset}".chomp
end

def red
  "\e[01;31m"
end

def green
  "\e[01;32m"
end

def reset
  "\e[00;m"
end
